name: loan_calculator
description: "برنامه محاسبه اقساط وام، سود سپرده و جریمه"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.19.0
  shamsi_date: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true